version: '2.3'

services:
  neural_nets:
    restart: always
    container_name: remainder_models
    mem_limit: 4G
    build:  
      context: ./models
      dockerfile: Dockerfile
    image: remainder_models:latest
    volumes:
      - ./models:/models
    command: python3 -u main.py

volumes:
  cache:
    driver: local